# Generated by Django 5.2.12 on 2026-03-28 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HoleStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hole_number", models.IntegerField()),
                ("par", models.IntegerField()),
                ("distance_in_yards", models.IntegerField(default=0)),
                ("gir_hit", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Round",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("course_name", models.CharField(max_length=255)),
                ("tee_name", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                ("is_complete", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Putt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("putt_number", models.IntegerField()),
                ("distance_ft", models.DecimalField(decimal_places=1, max_digits=6)),
                ("made", models.BooleanField(default=False)),
                (
                    "hole_stat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="putts",
                        to="rounds.holestat",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="holestat",
            name="round",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="holes",
                to="rounds.round",
            ),
        ),
    ]
