# Generated by Django 5.2.12 on 2026-03-28 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rounds", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="holestat",
            name="pin_position",
            field=models.CharField(
                choices=[("front", "Front"), ("middle", "Middle"), ("back", "Back")],
                default="middle",
                max_length=10,
            ),
        ),
    ]
